### ISSUE TITLE
Add hreflang tags in the XML Sitemap when Babel is installed

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#109]
Google allows to show hreflang tags in your XML sitemaps: https://support.google.com/webmasters/answer/2620865

This could be added in XML Sitemaps: check if Babel is installed and if a resource has a translated version somewhere. In that case, a hreflang tag can be added.

**Comment by degoya** [comment]
https://github.com/Sterc/SEOTab/issues/67

**Comment by gpsietzema** [comment]
Thanks @degoya !
