### ISSUE TITLE
Installation fails when AdminTools is installed

### ISSUE THREAD

**Issue by rthrash** [Sterc/SEOTab#114]
When trying to install into a site, it would not work until I uninstalled AdminTools:

https://modstore.pro/packages/utilities/admintools

Once it was uninstalled, SEOTab installed as expected.

**Comment by joeke** [comment]
Hi Ryan, do you have any errors in your error log or in your browser console when doing this?

**Comment by sdrenth** [comment]
Hi @rthrash can you confirm that this issue still applies and what error you are getting? I just installed AdminTools in a fresh 2.6.5 environment and I then could install SEOTab without a problem.

**Comment by sdrenth** [comment]
I'll close this issue due to inactivity, please let us know if the issue still remains, than I'll reopen this issue.
