### ISSUE TITLE
301 Redirect Fails

### ISSUE THREAD

**Issue by Alex740il** [Sterc/SEOTab#116]
Updated to latest version, red bar at top asking to migrate, clicking link to start migration does nothing. Stuck with message "SEO Tab was updated, but your 301 redirects need to be migrated. Click here to start the migration." and no way to get rid of it, unless I complete remove package. Reinstalling doesn't help...

**Comment by joeke** [comment]
Hm that sounds strange.. did any redirect urls get migrated? Do you see any urls in the SeoTab redirects cmp? And do you have any errors in your browser console when visiting the migrate page?

**Comment by Alex740il** [comment]
I cant tell, when I try to open the SeoTab 301 Redirects page, its blank. Nothing ever loads...

**Comment by designmich** [comment]
Redirect doesn't work.

1. Redirects doesn't work. I Always see the default error page of my website instead of the page wehen trying to load the url from the 301 tab
2. Automaticly added 301 doesn't use the original path of the page e.G. news/name-of-news

**Comment by Shiriaev** [comment]
301 redirect doesn`t correct creted for https. It add address http://mysite.com instead https://mysite.com. 
'server_protocol' option set to 'https', modx 2.5.7

**Comment by joeke** [comment]
@Shiriaev Do you mean the Old url field in the popup window in the CMP? That value gets prefilled with your site_url setting. Could you check what that value is?

**Comment by Shiriaev** [comment]
I have rihght site_url (i use it in base_href meta tag and it set https://mysite.com/). Its set wrong address in document page on SEO tab --> 301 redirect, when i change alias for document

**Comment by sdrenth** [comment]
@Alex740il @Shiriaev Does this issue still apply?

**Comment by sdrenth** [comment]
I'll close this issue due to inactivity
