### ISSUE TITLE
301 Redirects not created

### ISSUE THREAD

**Issue by rthrash** [Sterc/SEOTab#117]
Fresh install, fresh imported Resources.

Only SEO Tab and TinyMCEWrapper installed. Nothing else.

Changed the alias of a nested resource which I had created a manual redirect for and saved the resource with no issues. However when checking the 301 Redirects, I did not see a new entry for the change.

In addition, several errors were reported in the Manager log:

```[2017-03-14 19:56:02] (ERROR in modContext::makeUrl @ /www/core/model/modx/modcontext.class.php : 321) Resource with id 9 was not found in context mgr
[2017-03-14 19:56:02] (ERROR in modContext::makeUrl @ /www/core/model/modx/modcontext.class.php : 321) Resource with id 46 was not found in context mgr
[2017-03-14 19:56:11] (ERROR in modContext::makeUrl @ /www/core/model/modx/modcontext.class.php : 321) Resource with id 46 was not found in context mgr
[2017-03-14 19:56:19] (ERROR in modContext::makeUrl @ /www/core/model/modx/modcontext.class.php : 321) Resource with id 9 was not found in context mgr
```

Both Resource IDs exist in the site tree, and ID 46 was the resource I was changing the alias on.

**Comment by joeke** [comment]
That error seems like it can't find the right context for the resource id. I'll see if I can replicate this behaviour and will get back to you.

**Comment by jdaehne** [comment]
I have the same errors with MODX 2.5.5. No 301 are working.

**Comment by EkoOne** [comment]
I'm also having a 301 related issue (Revo 2.5.8 / SEO Tab 2.0.3), though mine is slightly different from those above.

I manually created a couple dozen redirects. They were all correctly saved, I can view them in the Manager, but when I visit the old url I'm not being redirected. I get a 404.

**Comment by gpsietzema** [comment]
@EkoOne Do you have some more details? What are the old URL's? Also, can you show us how they are saved in your database (modx_seo_urs table). Do you have multiple contexts?

**Comment by EkoOne** [comment]
- Only one context (web).
- A screenshot of the db table [modx_seo_urls](https://goo.gl/7QYDKT).
- The old urls pertain to a blog (created with the Articles Extra). For example, this is the old blog address [https://princetonfamily.com/blog/](https://princetonfamily.com/blog/), but the new one [https://princetonfamily.com/articles/](https://princetonfamily.com/articles/) swapped the word "blog" for "articles" in the url.

**Comment by sdrenth** [comment]
@rthrash @EkoOne @jdaehne Does this issue still apply?

**Comment by jdaehne** [comment]
@sdrenth i can confirm, that this issue still exists on a site i just tested:
- MODX: 2.6.5
- SEO Tab: 2.1.0

- Only one context: web

**Comment by EkoOne** [comment]
@sdrenth I too can confirm this issue using the same setup as @jdaehne.

**Comment by sdrenth** [comment]
@jdaehne So you are still receiving this error:
`Bad link tag [[~]] encountered`

When do you receive this error and can you provide me perhaps with some steps so I can possibly reproduce this error?

@EkoOne So you're having issues with 301 redirects.

Can you provide me with some example URL's which are not working?
So for example:
https://www.example.com/redirect-url --> https://www.example.com/new-page

**Comment by sdrenth** [comment]
@jdaehne Are you sure the `Bad link tag` error is related to SEO Tab? Because SEO Tab only sets the `[[+seoTab.robotsTag]]` placeholder and doesn't use links like this: `[[~[[+id]]]]`.

The Bad link tag error is caused when for example the id placeholder is not set, so it will try to parse: `[[~]]`. Perhaps you can try to disable SEO Tab plugin and see if the error still exists, but I think this is an issue in your template/chunks.

Please provide me with some redirect URLs that are not working so I can look into that.

**Comment by EkoOne** [comment]
@sdrenth I'm currently traveling so I can't provide any urls.

**Comment by jdaehne** [comment]
@sdrenth you are right. That can't come from seoTab.

i tested it on an fresh install of MODX: There are no errors like that in the errorlog. So please ignore this issue. That probably is caused from something else.

**Comment by sdrenth** [comment]
@jdaehne Glad to hear! Thank you for checking it in a fresh install!

@EkoOne Is it possible now that you can provide some URL's which are not being redirected so we can look into that?

**Comment by EkoOne** [comment]
Ok, here are a couple urls on two different sites that are not redirecting:

Old [https://qreativ.space/reviews/hardware/network/bitdefender-box-2-review.html](url) -> New [https://qreativ.space/reviews/hardware/network/bitdefender-box-2.html](url)

Old [https://princetonfamily.com/articles/2011/01/14/fragmented-lives-i/](url) -> New [https://princetonfamily.com/articles/2011/01/14/fragmented-lives/](url)

**Comment by sdrenth** [comment]
@EkoOne Okay, seems to be a quite simple redirects to me, i've tested with similar URL's and I cannot reproduce your issue.

We are releasing a new version of SEO Tab shortly, I'd recommend you to install this new version and see if this might fix your issue, it contains a fix where it doesn't strictly match the server protocol of an URL so that might fix your issue as well.
