### ISSUE TITLE
Change default settings for Freezy URL

### ISSUE THREAD

**Issue by Prubtsov** [Sterc/SEOTab#119]
Hello! How to change default settings for Freezy URL to disable it? I use StercSEO in pair with Articles. I need only short link (https://mysite/events/2017/04/07/URLpost/), without the "date" and "events" in the link (events/2017/04/07/). Thanks!

**Comment by sdrenth** [comment]
@Prubtsov If I understand you correctly you are looking for some automated way for generating Freeze URI's for nested resources? SEO Tab does not provide any options for the Freeze URI field that would make this possible.
