### ISSUE TITLE
Can't read Google preview

### ISSUE THREAD

**Issue by crecorn** [Sterc/SEOTab#122]
After upgrading to 2.01 there is a pattern graphic behind the google preview title. Not a big deal, I know what it says. Just odd.

![screenshot of editing- office copiers printers scanners data backup - valley office solutions](https://cloud.githubusercontent.com/assets/1356816/26044147/8f13a9e0-3910-11e7-9ffc-bc99b620e675.jpg)

**Comment by joeke** [comment]
I think you're mistaking SEO Tab with SEO Pro. Did you happen to update SEO Pro as well? There we introduced an update where a favicon appears when using Yandex as search-engine. Nevertheless, I think clearing your browser cache should resolve the issue.

**Comment by crecorn** [comment]
Yep, I clicked the wrong link. I'll try clearing the cache. Thanks. By the way, great job on these extras, they are a must to install on all my sites.

**Comment by joeke** [comment]
Closing this because it's a SEO Pro issue.
