### ISSUE TITLE
>50K of Resources breaks Google Sitemaps

### ISSUE THREAD

**Issue by rthrash** [Sterc/SEOTab#125]
Google errors on sitemaps that contain more than 50,000 URIs … don't ask how I know this :P 

It would be super-useful for high volume publishers to have access to a few parameters to better manage how sitemaps are built. Perhaps something to include specific resource IDs, and certain parents, sort of like getResources or pdoTools:

`&includeIDs` – specific resource IDs to include in the sitemap
`&parents` – specific parents and all descendant Resources to include in the sitemap

… or something along those lines.

**Comment by m-engel** [comment]
Think you know it from google themself written in their docs ,-) 
https://support.google.com/webmasters/answer/183668

Another approach:
If Results > 50.000 or maybe better an property "&largeSitemap" is set:
generate at the main document an sitemap index document, and generate the sitemaps below the same file with parameters like "&map=1" all sub-Sitemaps in 50k Steps which results with an maximum of 500 Sub-Sitemaps as 25.000.000 Documents.

**Comment by gpsietzema** [comment]
Good one Michael. We were advised to do exactly what you're stating.
