### ISSUE TITLE
Noodp & Noydir

### ISSUE THREAD

**Issue by jonleverrier** [Sterc/SEOTab#126]
Consider dropping Noodp & Noydir from the default robots meta tag.

**Noodp= No Open Directory Project**
DMOZ shutdown on March 14th 2017

**Noydir= No Yahoo Directory**
Yahoo Directory shutdown on December 31 2014

**Comment by jonleverrier** [comment]
Quick hack, without having to edit the plugin default values:

[[+seoTab.robotsTag:is=`noopd,noydir`:then=``:else=`<meta name="robots" content="[[+seoTab.robotsTag:replace=`noopd,noydir,==`]]">`]]

**Comment by gpsietzema** [comment]
Good idea @jonleverrier We'll include it in our next release.

**Comment by sdrenth** [comment]
Since noopd and noydir already have been dropped this issue can be closed.
