### ISSUE TITLE
bug : stercseo.hide_from_usergroups

### ISSUE THREAD

**Issue by julienstuder** [Sterc/SEOTab#128]
doesn't seem to have any effect... ?

**Comment by joeke** [comment]
@julienstuder I just tested it on my local machine with the latest version (2.0.3) and works fine. 
Are you sure you've entered the usergroup name correctly? Here's my example:
![screen shot 2017-09-13 at 18 04 35](https://user-images.githubusercontent.com/2332231/30387819-14682e3e-98ae-11e7-954d-7c46a1eeb6b1.png)
This hides it from all users in the Administrator usergroup.
Maybe some error in your browser console? Or perhaps your browser/modx cache..

**Comment by julienstuder** [comment]
Ho thanks for the test !

My bad, I had put the uaergroups ID’s !!!

Thanks a lot !





Julien Studer
NoPixel
Rue de l’Hôpital 14
2800 Delémont
032 422 91 20
JOIGNABLE DE PREFERENCE SUR MOBILE:
078 722 62 33

www.nopixel.ch <http://www.nopixel.ch/>
