### ISSUE TITLE
XML Sitemaps are shown in page sitemap

### ISSUE THREAD

**Issue by sdrenth** [Sterc/SEOTab#131]
If "Include this page in the Google Sitemap?" is set to yes, the sitemaps can also be shown in Googlesitemaps, but when you set the value to No it will not be shown in Index XML sitemap.

Can you please edit the following code in the buildquery method in order to ignore google sitemap property when the sitemap type is set to index:

```
/** Change this. */
$c->where(
	array(
		array('context_key:IN' => $contextKey, 'published' => 1, 'deleted' => 0),
        array('properties:LIKE' => '%"sitemap":"1"%', 'OR:properties:LIKE' => '%"sitemap":null%', 'OR:properties:IS' => null)
	)
);


/** To this: */
$c->where(
	array(
    	array('context_key:IN' => $contextKey, 'published' => 1, 'deleted' => 0),
	)
);

if ($options['type'] !== 'index') {
    $c->where(
    	array('properties:LIKE' => '%"sitemap":"1"%', 'OR:properties:LIKE' => '%"sitemap":null%', 'OR:properties:IS' => null)
	);
}
```

**Comment by MrRoco** [comment]
Hello Sander,

I've added it to the roadmap for future releases.

**Comment by sdrenth** [comment]
This fix has been merged and will be included in the next release.
