### ISSUE TITLE
Changing alias does not always create redirect

### ISSUE THREAD

**Issue by joeke** [Sterc/SEOTab#132]
In some cases when changing the alias there isn't an automatic redirect created. In my quick test this only seemed to happen when the resource did not have child resources. When it did have child resources the redirects for all children were correctly created.

**Comment by sdrenth** [comment]
@joeke Possibly related:

- Issue: https://github.com/Sterc/SEOTab/issues/148
- PR: https://github.com/Sterc/SEOTab/pull/164

**Comment by sdrenth** [comment]
@MrRoco Can you check if this issue is solved with PR #164? Please close this issue if it is fixed now.

**Comment by gpsietzema** [comment]
Re-tested with the 2.2.0 build and this isn't an issue anymore.
