### ISSUE TITLE
redirect does not work if the container alias and any get parameter are present in the URL

### ISSUE THREAD

**Issue by Semdevmaster** [Sterc/SEOTab#133]
Hi, I like your component and I would like to help improve it.
I'm not a programmer, so I will describe one thing that I noticed.
There is a category - news
url - https://site.ru/news
Each news has an URL of the following type: https://site.ru/news/?Id=1
After changing url, we have https://site.ru/news/news_one
Now we try to enter the old URL in the browser, but the redirect does not work, although there is a rule created in the table of seoTab.

**Comment by sdrenth** [comment]
@arsentver I'm not sure if I understand you correctly, but I've tested a 301 redirect which contains a GET parameter which worked as expected. I'll close this issue for the time being. Please let us know if this issue still remains, then I'll reopen this issue.
