### ISSUE TITLE
Redirect migration page not always returns success message

### ISSUE THREAD

**Issue by joeke** [Sterc/SEOTab#136]
In some cases the redirect migration page does not return success when migration is complete and therefore does not show the success popup.

**Comment by gpsietzema** [comment]
@joeke Can you make this more specific? 'Some' is a bit vague :)

**Comment by joeke** [comment]
@gpsietzema I've heard it from other people (here at Sterc) when performing the migration.. didn't have the issue myself, but I have the feeling it has something to do with the combination of checking for migrate-able redirects and checking the migration_status system setting. I think it could be tested by importing some old-style redirects (in the resource table) from an old backup, install the latest 1.x seotab and then upgrading to the latest version.
