### ISSUE TITLE
301 redirects automatically added for new resources when not required

### ISSUE THREAD

**Issue by Citric** [Sterc/SEOTab#137]
After checking the Extras > SEO Tab within the Modx manager, there's a list of 301s that were created automatically for some reason. Also, when testing by adding a new resource, it's also added to this list.

It seems to be redirecting the resource ID, eg. domain.com/10 .

Is this intentional as people would be accessing the resource via the friendly URL and not ID as it wouldn't be known?

There doesn't appear to be a config setting for this either.

**Comment by gpsietzema** [comment]
Hello @Citric 

Whenever the resource alias or uri changes, it is automatically added as a 301 redirect to avoid 404 pages. This also applies to dragging & dropping. You can't disable this by changing a setting.

Not really sure if that's what your saying though. Are you saying it isn't following the rules above?

**Comment by Citric** [comment]
Thanks for clarifying, that is the behaviour we're seeing.

Is there a way to bulk remove the redirects from the list?

**Comment by gpsietzema** [comment]
Alright. Bulk-removing isn't a feature unfortunately. You cán use the component provided to see all 301's in one place and remove 'm from there. To use that, click the menu 'Extras' on the top and click 'SEO Tab'. There is a filter available where you can search.

**Comment by Citric** [comment]
That's how we're doing it at the moment so it might be worth considering a checkbox to bulk remove.

**Comment by gpsietzema** [comment]
I'll add it to our roadmap, thanks!
