### ISSUE TITLE
Sitemap and robots clash

### ISSUE THREAD

**Issue by getandyjones** [Sterc/SEOTab#138]
Hi there,
I can't work out form the docs - but if I set no follow, no index within findability, why does this resource still appear in my sitemap.xml?

Also, I am required to have a robots.txt in the doc root, but does this mean that the robots meta won't work?

Thanks
Andy

**Comment by gpsietzema** [comment]
They are two different things.

We discussed this with the team a while ago and could think of situations where you would want noindex, but still want to have them in your sitemap to follow links. Didn't think of both noindex and nofollow though. I currently can't think of a reason why I'd want a page in the sitemap when they are both set to no. I'll have it added for the next release.

**On robots.txt**
We're currently not infuencing the robots.txt file with SEO Tab.

**Comment by devlanda** [comment]
This issue is fixed with https://github.com/Sterc/SEOTab/pull/168 and will be distributed in the next release of SEOTab.
