### ISSUE TITLE
500 Error on Install

### ISSUE THREAD

**Issue by kelly8116** [Sterc/SEOTab#139]
When I install the latest version of SEOTab (2.0.4), the entire site crashes and I have to remove the plugin completely. If I install version 2.0.3, everything seems to work except the 301 redirects.

I get these errors on install:

`mod_fcgid: stderr: PHP Fatal error:  Can't use method return value in write context in /full/path/core/model/modx/processors/security/user/getonline.class.php on line 15, referer: http://66.132.193.85/manager/`

`mod_fcgid: stderr: Cache couldn't make dir '/file/path/core/cache/rss/'., referer: http://66.132.193.85/manager/`

When I try to load the page, I get this error:

`mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '[' in /file/path/core/components/stercseo/model/stercseo/stercseo.class.php on line 493`

I have this issue running ModX 2.5.8 and 2.6.0.

**Comment by MrRoco** [comment]
Hello Kelly,

Thank you for reporting this error.
I've added it to our roadmap for future releases to have it resolved.

**Comment by MrRoco** [comment]
Hello Kelly,

Your installation error is fixed in the released version of  SEOTab 2.0.5

**Comment by Quentin100** [comment]
Hi @MrRoco,

Where can I get SEOTab 2.0.5 as I have this same problem.

Thanks,

Quentin

**Comment by kelly8116** [comment]
Version 2.0.5 has the same issue on line 514.

`mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '[' in /file/path/core/components/stercseo/model/stercseo/stercseo.class.php on line 514`
