### ISSUE TITLE
New Url/Resource not set properly with paginated results in CMP

### ISSUE THREAD

**Issue by sdrenth** [Sterc/SEOTab#141]
When updating a redirect with a new Url/Resource that is not being retrieved within the first page of the combobox the value is not being displayed properly. 

I'd suggest to add the value as a param to the resourcelist processor and include the object in the results returned from the processor if it does not exists already in the results from the processor.

![screen shot 2017-12-21 at 08 00 03](https://user-images.githubusercontent.com/7802465/34244308-f9f07d44-e624-11e7-9397-17f668be6e15.png)

**Comment by MrRoco** [comment]
Hello Sander,

Added to our roadmap.
