### ISSUE TITLE
Empty sitemap after update to PHP 7.2.1

### ISSUE THREAD

**Issue by degoya** [Sterc/SEOTab#146]
After updating my Modx to 2.6.1 and switching to PHP 7.2.1 the generated Sitemap ist Empty.
Are there any known Bugs for SEOtab and PHP 7.2 ?

i have tried several settings 

[[!StercSeoSiteMap]]

[[!StercSeoSiteMap? &contexts=`de` &allowSymlinks=`0`]]

The Result looks always like this

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</urlset>

anything i missed on updating?

**Comment by johanmolen** [comment]
Hello @degoya,

Do you see any errors in the MODX error log or the PHP error log?
And could you provide a link to the sitemap?

**Comment by degoya** [comment]
There are no errors on Modx Error log nor PHP Error log. 
Here is the link to the generated Sitemap.
https://xxxxx.de/sitemap.xml

i've just got the same problem on another updated site, no errors but also no sitemap.

**Comment by gpsietzema** [comment]
We just had the same issue on a local 7.2 environment. We haven't currently scheduled any time for this, but it is on top of our list for SEOTab.

**Comment by johanmolen** [comment]
@degoya this is exactly a problem within XPDO in combination with PHP7.2. We addressed this issue to MODX. 

If you want to keep PHP7.2 then you can find the fix here:
https://github.com/modxcms/xpdo/issues/135

But my opinion would be to wait with the PHP7.2 upgrade till MODX releases a new version with better PHP7.2 support. MODX has multiple flaws with PHP7.2 at the moment, mostly deprecated code.

**Comment by sdrenth** [comment]
Since this issue is not related to SEO Tab we will close this issue.
