### ISSUE TITLE
301 redirects are being removed onDocFormSave if cache_alias_map is set to yes

### ISSUE THREAD

**Issue by sdrenth** [Sterc/SEOTab#148]
## Behaviour
Changing an alias of a resource was not generating a 301 redirect.

## Explanation
After debugging I found out that the 301 redirect was actually being generated during the OnBeforeDocFormSave event. But during the OnDocFormSave event it was being removed again from the redirects table. This is happening because the makeUrl method was retuning an old URL and not the new URL using the new alias. The old URL is being retrieving because the system setting "cache_alias_map" was set to Yes. Changing the setting to "No" fixed the issue.

## Possible fix?
Perhaps the plugin can first retrieve the system setting value, then set it to no and after the makeUrl method set the system setting back to its original value?

**Comment by davidpede** [comment]
Just came here to report same issue: cache_alias_map = yes stops auto 301 generation
