### ISSUE TITLE
Alias not found errors

### ISSUE THREAD

**Issue by davidpede** [Sterc/SEOTab#149]
Any resources in mgr context that have a 301 redirect in place is causing an error in modx log when edited. 

Error is: ``` [2018-04-24 08:09:58] (WARN @ /core/model/modx/modcontext.class.php : 244) `20` was requested but no alias was located. ```

MODX 2.6.1-pl - PHP 7.1

**Comment by sdrenth** [comment]
@davidpede I can confirm this issue with MODX 2.6.5 and SEO Tab 2.1.0 when the `log_level` system setting is set to 2 (warning)

**Comment by sdrenth** [comment]
I've added a PR which fixes the warning. After it is merged it will be added in our next release.
