### ISSUE TITLE
Feature request: make all resource fields available as placeholders for the sitemap rowTpl

### ISSUE THREAD

**Issue by alipang** [Sterc/SEOTab#150]
I'm trying to make my sitemap a little more human readable and have added a xsl stylesheet and a xsd with xml extensions. My goal is to display the pagetitle instead of the url, however [[+pagetitle]] doesn't seem available.

[[+id]] would be enough. The rest can be accomplished with output modifiers.

And also it would be nice to be able to sort urls by loc.

**Comment by sdrenth** [comment]
I've added a PR which adds all resource fields to the row chunk. After it has been merged it will be added in our new release.
