### ISSUE TITLE
PHP Undefined index: HTTPS

### ISSUE THREAD

**Issue by christianseel** [Sterc/SEOTab#153]
StercSEO Plugin throws a notice at

```
$url = ($_SERVER['HTTPS'] ? 'https' : 'http').'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
```

```
/core/cache/includes/elements/modplugin/13.include.cache.php : 243) PHP notice: Undefined index: HTTPS
```

It should be checked if the HTTPS property exists.

Notice occurs on local vagrant box running Apache.

**Comment by sdrenth** [comment]
Hi @christianseel, 

I've justed created a PR which will fix the notice. After it has been merged it will be in our next release.
