### ISSUE TITLE
$urls is undefined

### ISSUE THREAD

**Issue by cured** [Sterc/SEOTab#173]
Hello
following https://github.com/Sterc/SEOTab/issues/142
i got the same issue except that it occurs when i try to create new resource
stercseo-2.1.0-pl
modx revolution-2.6.5 pl
php 7.1.25

**Comment by gpsietzema** [comment]
@cured can you give me a list of extras you're using? I'm suspecting conflicting extras is the issue.

**Comment by devlanda** [comment]
Closed due to inactivity.
