### ISSUE TITLE
Special symbols in URL 

### ISSUE THREAD

**Issue by wax100** [Sterc/SEOTab#175]
When it is special symbol in URL , redirect dont work
So I have to add 2nd record manually and then it works
![image](https://user-images.githubusercontent.com/4846064/51820686-a86cc080-22e7-11e9-9d08-7dde69d94eb5.png)

**Comment by devlanda** [comment]
It seems that characters like 'å' and 'ø' don't work too.

**Comment by haeki1** [comment]
Same here. Anything new on this one?

**Comment by haeki1** [comment]
Just figured it out. It’s been line 261 in stercseo.plugin.php. Added urldecode here.
`$url     = urldecode($_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);`

Can this maybe be added to feature releases?

**Comment by devlanda** [comment]
Thank you @haeki1.
