### ISSUE TITLE
remanent plugin when uninstalled package

### ISSUE THREAD

**Issue by elz64** [Sterc/SEOTab#36]
Since I de installed Setrc CEO (Revo 2.31),  [nb: just setup it to see what it was]
 it seams to remains 'somewhere'  and cause errors for every actions on the site.

** The uninstall does not remove the plugin  **

Here's the error in an 'infinite' list in modx error log.
[2014-11-06 15:44:52] (ERROR @ /index.php) Problem getting service stercseo, instance of class StercSEO, from path /var/www/vhosts/xxxxx.fr/yy.xxxxx.fr/core/components/stercseo/model/stercseo/
[2014-11-06 15:45:19] (ERROR @ /index.php) Error caching lexicon topic lexicon/en/wayfinder/properties

SO I did deactivated this plugin, and cleared the cache.. now,  errors seams to go away

**Comment by sdrenth** [comment]
Hi @elz64 

I've tested it and the plugin is indeed not removed or disabled. We will fix this issue in a later release.

Thanks for reporting!

**Comment by sdrenth** [comment]
I've noticed  that uninstalling the package is working correctly. If you remove the package without checking Force package removal, then everything is also removed correctly. If you do check this option, the package will not be uninstalled but will just remove the package transport.

So be sure to uninstall the package and not check "Force package removal"
