### ISSUE TITLE
Disregard depending from parent resource

### ISSUE THREAD

**Issue by Setest** [Sterc/SEOTab#37]
In the derivation of the sitemap does not pay attention to what is published whether a parent or not, brings everything based only on the status of the publication of the current resource and its properties.

**Comment by joeke** [comment]
Hi Setest. This could be a nice feature, but something that has to be turned on or off via for instance a system setting. I can imagine situations where you want a subpage to be indexed and published, but not the parent page. For instance if you have a folder with landingspages.

**Comment by devlanda** [comment]
This issue is fixed with https://github.com/Sterc/SEOTab/pull/171 and will be distributed in the next release of SEOTab.
