### ISSUE TITLE
 How does Sterc SEO Tab works? (RTFM)

### ISSUE THREAD

**Issue by vierkantemeter** [Sterc/SEOTab#4]
I'm checking out Sterc SEO Tab 1.0.0, but there isn't any documentation. How do I use this add-on?

(See forum post here: http://forums.modx.com/thread/88182/how-does-sterc-seo-tab-works-rtfm)

**Comment by Prubtsov** [comment]
Hello! How to change default settings for Freezy URL to disable it? I use StercSEO in pair with Articles. I need only short link (https://mysite/events/2017/04/07/URLpost/), without the "date" and "events" in the link (events/2017/04/07/). Thanks!
