### ISSUE TITLE
301 redirects not automatically created

### ISSUE THREAD

**Issue by vierkantemeter** [Sterc/SEOTab#42]
The 301 redirects are not automatically created when the page alias is changed. 

But, there is a 301 created when freeze URI is set. But shouldn't there always be a 301 created when the alias changed regardless of the freeze URI setting? Like hear your thoughts about this. 

MODX 2.3.3
Seotab 1.1.0

**Comment by mazuhl** [comment]
+1, interested in this.

**Comment by sdrenth** [comment]
Hi @vierkantemeter and @mazuhl,

Thats a great idea, it will be added in the new release!
