### ISSUE TITLE
301 settings in resource get lost in modx 2.3.3

### ISSUE THREAD

**Issue by degoya** [Sterc/SEOTab#43]
i don't know why but some times the old urls are not working anymore after a while and when i check the 301 list is empty.
happens in modx 2.3.3.

**Comment by matdave** [comment]
I see this happen too.  If you open a page, edit and save it without opening the SEO Tab it seems to drop the 301 Redirects.

**Comment by gpsietzema** [comment]
This should be fixed by todays release.
