### ISSUE TITLE
Can't exclude the sitemap itself from indexing

### ISSUE THREAD

**Issue by Gallenkamp** [Sterc/SEOTab#45]
Sitemap itself is beeing indexed:

http://vonbohr-fescharek.de/sitemap.xml

Both settings are set to "no", regarding indexing. Sitemap is published but not visible in menu.

**Comment by Gallenkamp** [comment]
For now, I copied the sitemap output, edited and published a hardcoded version.

**Comment by Bumme** [comment]
Could you check if it's fixed in the new release? I can't reproduce this issue.

**Comment by sdrenth** [comment]
@Gallenkamp is this issue fixed now with the latest release? Else i'm going to close this issue

**Comment by Gallenkamp** [comment]
Will check immedieately.

**Comment by Gallenkamp** [comment]
Sitemap can be excluded. Thank you!

**Comment by sdrenth** [comment]
Glad to hear! ;)
