### ISSUE TITLE
Visual errors with MODX 2.4

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/SEOTab#47]
The component is no longer usable in this version of MODX.  
![screen shot 2015-08-20 at 16 01 25](https://cloud.githubusercontent.com/assets/447453/9385103/be132536-4754-11e5-965d-088391057905.png)

**Comment by matdave** [comment]
I don't know that it matters what version of MODX, it appears to just have coincided with a recent update.  the main culprit is:

<pre>#seo-tab .vertical-tabs-header{padding-bottom: 200px !important;}</pre>

**Comment by Bumme** [comment]
@sonicpunk What version do u use?

**Comment by adamwintle** [comment]
I'm also seeing this on MODX 2.4.0 and SEO Tab 1.1.2-pl

**Comment by sonicpunk** [comment]
Yes, I have the latest versions, so MODX 2.4 and SEO Tab 1.1.2-pl

**Comment by DESIGNfromWITHIN** [comment]
Same here
![screen](https://cloud.githubusercontent.com/assets/725851/9518749/b53d3446-4cb9-11e5-8051-1a9a296f0875.jpg)

**Comment by Bumme** [comment]
Will release today a new version
