### ISSUE TITLE
Use StercSeoSiteMap to generate a HTML sitemap

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [Sterc/SEOTab#49]
It would be cool to be able to also generate a HTML sitemap based on SEOTab settings...

Any plan for this?

**Comment by sdrenth** [comment]
Hi @DESIGNfromWITHIN,

That indeed would be a nice feature for SEOTab, we will add this feature to the package!

**Comment by joeke** [comment]
hey Menno,
This is now partly possible with the `outerTpl` and `rowTpl` parameters, although then you won't have resource hierarchy, and no pagetitle for the resource. So I think it's better to generate the HTML sitemaps with Wayfinder or pdoMenu. To get the same results as the StercSeoSiteMap you'll have to use a where clause which checks for the `sitemap: 1` property on the resource. I think I'll put some example snippet calls for Wayfinder and pdoMenu in the readme.
