### ISSUE TITLE
Missing default setting for show in internal search

### ISSUE THREAD

**Issue by rthrash** [Sterc/SEOTab#51]
I am not seeing a default setting for `Include pages in internal search engines`.

![editing__home___modx_revolution](https://cloud.githubusercontent.com/assets/234237/11855117/e0a019cc-a40d-11e5-8003-982dec6bff81.png)

Here's the settings listed under StercSEO namespace:

![system_settings___modx_revolution](https://cloud.githubusercontent.com/assets/234237/11855136/09c3fe04-a40e-11e5-925f-d7a8db335a5f.png)

I believe the relevant section of code comes from `assets/components/stercseo/js/mgr/sections/resource.js`:

```
                    },{
                        xtype: 'modx-combo'
                        ,name: 'searchable'
                        ,hiddenName: 'searchable'
                        ,fieldLabel: _('stercseo.searchable')
                        ,store: new Ext.data.SimpleStore({
                            data: [
                                [1, _("stercseo.searchable_yes")],
                                [0, _("stercseo.searchable_no")], ],
                            id: 0,
                            fields: ["value", "text"]
                        })
                        ,valueField: "value"
                        ,displayField: "text"
                        ,mode: "local"
                        ,value: Ext.getCmp('modx-panel-resource').record.searchable
                        ,listeners: {change: function(){MODx.fireResourceFormChange();}}
                        ,width: 400
                    },{
                        xtype: 'label'
                        ,forId: 'pagetitle'
                        ,text: _('stercseo.searchable_desc')
                        ,cls: 'desc-under'
                    }]
```

Or, does this default back to the searchable checkbox default value of the System Settings? `search_default` iirc…

**Comment by sdrenth** [comment]
Hi @rthrash,

The default setting for "Include pages in internal search engines" is indeed using the system setting 	
search_default and therefore has not it's own system setting in SEOTab.
