### ISSUE TITLE
feature request : apply rowTpl script parameter

### ISSUE THREAD

**Issue by carnevlu** [Sterc/SEOTab#52]
Hi,

we call the snippet `StercSeoSiteMap` wit the parameter `rowTpl`, but the alteration of the _template_ are not applied.

Can you add the feature to override the templates (outerTpl and rowTpl)?

**Comment by sdrenth** [comment]
Hi @carnevlu,

Setting the outerTpl and RowTpl will be added to the new release. Thank you for your feature request!
