### ISSUE TITLE
SEO Tab is not displaying correctly in  2.4.2

### ISSUE THREAD

**Issue by roydegler** [Sterc/SEOTab#54]
SEO Tab is not displaying correctly since upgrading to 2.4.2, I have the latest version of SEO Tab 1.2.2 installed.

Here is a screen capture of the manager screen:

http://screencast.com/t/3cxCeUrCZWYB

Roy

**Comment by joeke** [comment]
Hi Roy,
Indeed, that doesn't look right ;).
I've done a quick test with a fresh modx 2.4.2 install, and installed SEOTab 1.2.2, but everything looks fine here (on Chrome 47, and IE11). 
Which browser do you use? And have you cleared your Modx cache and your browser cache after upgrading?

**Comment by roydegler** [comment]
The issue was clearing the Modx cache.  I thought that had be done by the individual that just completed the upgrade to 2.4.2.
Thanks for the quick reply

Roy Degler
roy.degler@okstate.edu<mailto:roy.degler@okstate.edu>
405 744-6541
Digital Library Services

Nothing exists except atoms and empty space; everything else is opinion.
Democritus
Greek philosopher (460 BC - 370 BC)


On Dec 22, 2015, at 3:23 AM, Joeke Kloosterman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Roy,
Indeed, that doesn't look right ;).
I've done a quick test with a fresh modx 2.4.2 install, and installed SEOTab 1.2.2, but everything looks fine here (on Chrome 47, and IE11).
Which browser do you use? And have you cleared your Modx cache and your browser cache after upgrading?

**Comment by joeke** [comment]
No problem Roy. Glad I could help ;)
