### ISSUE TITLE
301 ook vergelijken op complete url incl. TLD

### ISSUE THREAD

**Issue by andresterc** [Sterc/SEOTab#57]
Het is nu niet mogelijk om 2 dezelfde 301's in te stellen waarbij de TLD verschilt van elkaar.
.de?index=1 en .nl?index=1 mag niet ingevoerd worden, terwijl dit wel verschillend is aan elkaar.
Daarnaast wordt er niet gekeken naar de TLD op het moment dat een redirect binnen komt.

**Comment by joeke** [comment]
Dit wordt meegenomen in de nieuwe 2.0 versie van SEOTab.
