### ISSUE TITLE
redirect SEOTab does not work with contentblock

### ISSUE THREAD

**Issue by MrRoco** [Sterc/SEOTab#58]
The 301 doesn't always work in combo with contentblocks.
This is due to the url wildcard check of the converted url.

**Comment by degoya** [comment]
i used it with CB and didn't got any problems yet, anyone else can replicate this error?

**Comment by degoya** [comment]
got the same problem now, any fix available yet?

**Comment by Mark-H** [comment]
I haven't heard of this before, but let me know if you need any help. Can't say I know why these two extras would influence each other though, only thing that comes to mind is that they both write to the properties field?

**Comment by degoya** [comment]
i have tested several sites now and 301 not working anymore. at least i can say it worked when installed and tested them first. But most all of the sites got CB & SEOtab updates so maybe one of those changes produce errors now.

**Comment by degoya** [comment]
any one got a solution for this issue? would be great to use the 301 again :) but i could not find the root of the evil

**Comment by joeke** [comment]
@degoya This should be resolved when the 2.0 version of SEOTab is released, which is expected somewhere in the next few days. In this version all redirects are saved inside a separate table, so they shouldn't conflict with Contentblocks anymore.

**Comment by sonicpunk** [comment]
I can verify this issue!  Just launched a project that is affected by it.  Thanks for the info!

**Comment by degoya** [comment]
any idea when this will seotab2 will be finished?
and will seotab2 the redirects that have been added with seotab1? or do i need to set them again?

**Comment by joeke** [comment]
@degoya The 2.0 release is a bit delayed but we're finishing up on the latest issues now. And it includes a migration page which will migrate all your old seotab 1.x redirects to the new 2.0 format, so no need to set them again! We'll keep you posted on the 2.0 release.

**Comment by sonicpunk** [comment]
Can't wait for this!!!

**Comment by degoya** [comment]
Thanks for the Information, can't wait for the new release to get finally rid of my htaccess based 301 workaround :)
