### ISSUE TITLE
certain url's 301 's don't resolve 

### ISSUE THREAD

**Issue by hurby** [Sterc/SEOTab#59]
Example:

http://www.nicoprbakker.nl/index.php/columns/archief/470-belegger04april14 
as a 301 to http://www.nicoprbakker.nl/columns/belegger/ 

Don't work. Probably because of the index.php?

Thnx
Hurby

**Comment by joeke** [comment]
Hey @hurby 
This should be resolved with our new 2.0 version of SEOTab, where the redirects are stored in a separate table. I've just now pushed the last changes for the 2.0 version.. It will be available in the MODX repo somewhere in the next few days. I'll keep you posted!

**Comment by joeke** [comment]
@hurby I've been testing with the url you provided, and indeed the index.php in your redirect is a problem. Modx doesn't detect it as a 404 so it can't be redirected. I'm afraid this can't be solved in Seotab, so you'll have to use a custom rewriterule in your .htaccess file (or, if you're using nginx, a redirect in your nginx config).
