### ISSUE TITLE
Problems with SEO Tab in MODx MODX Revo 2.4.3

### ISSUE THREAD

**Issue by Brain8torm** [Sterc/SEOTab#60]
![2016-02-26_005633](https://cloud.githubusercontent.com/assets/571307/13335811/f6387132-dc23-11e5-9a66-e5c32b79583c.png)
After updating CMF to version MODX Revolution 2.4.3-pl (traditional), extension SEO Tab was incorrectly displayed on add/edit resource page as on the attached picture.

**Comment by frogabog** [comment]
Have you resolved this yet?  I saw that initially after updating, but clearing the cache, logging out and back in again resolved it.

**Comment by joeke** [comment]
@Brain8torm Do you still have this issue? As @frogabog points out, this looks like a caching issue due to updated styling for newer MODX versions.

**Comment by Brain8torm** [comment]
Hello! This problem was solved after updating this extension. Thank you! Probably it has been inconsistencies with the new design of the manager panel.
