### ISSUE TITLE
Including Page in search engines question

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/SEOTab#62]
There is the tab Findability where you can set the page to be found by search engines.  But then there is the Google Sitemap tab that also has a similar function.  When I have the setting set to yes on the Findablity tab, but No on the Google Sitemap tab, the page still gets listed in the XML produced by the snippet StercSeoSiteMap.

Am I missing something?

**Comment by joeke** [comment]
Hi @sonicpunk 
I can't seem to reproduce this issue. The sitemap snippet only checks if published = 1, deleted = 0, and if the 'include in sitemap' is checked. It doesn't do anything with the values from the Findability tab.
Maybe there's another plugin interfering with Seotab?
If you have access to your database you could check in the site_content table if the properties field is correctly saved with all the properties from Seotab.
