### ISSUE TITLE
"Default-Setting: Include pages in the Google Sitemap" assigned to "no" not working

### ISSUE THREAD

**Issue by ant5** [Sterc/SEOTab#64]
When I set "Default-Setting: Include pages in the Google Sitemap" to "no"  the StercSeoSiteMap generate sitemap of all resource regardless to this setting.

**Comment by DESIGNfromWITHIN** [comment]
Same issue here!

**Comment by joeke** [comment]
@ant5 @DESIGNfromWITHIN The setting is meant for the default setting when creating new resources. All existing resources will not be affected when changing this setting. The sitemap snippet checks the value that is saved with the resource, and does not check the system settings.

**Comment by gpsietzema** [comment]
@ant5 @DESIGNfromWITHIN Would it be an enhancement if SEO Tab offered to set all existing resources to your default value on install?
