### ISSUE TITLE
SEOTab is not visible in my resources

### ISSUE THREAD

**Issue by ravikandel1** [Sterc/SEOTab#68]
I am using Modx Revo 2.5.1 pl. Please help i have installed SEOTab through package Management...

**Comment by gpsietzema** [comment]
@ravikandel1 Some questions:
- Is the plugin active?
- Are you getting javascript errors?
- Are you getting errors in your MODX error log
- Server errors?
- Tried reinstalling?

**Comment by ravikandel1** [comment]
Yes I tried all you mean but it is not visible.... By the way... the SEO Tab is not visible and it is not showing any error. I want the SEO Tab visible in resource. Please Help

**Comment by gpsietzema** [comment]
@ravikandel1 We need more info to be able to help you.
