### ISSUE TITLE
The context-dropdown isn't big enough

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#70]
The context-dropdown isn't big enough. There is enough space, so it should just be made a little wider.

![screen shot 2016-10-25 at 14 42 55](https://cloud.githubusercontent.com/assets/381017/19686433/69f0a688-9ac1-11e6-8a4b-87963c99ab2d.png)

**Comment by gpsietzema** [comment]
It is fixed-width. Can't it just auto-expand? 

<img width="318" alt="screen shot 2017-01-19 at 21 23 44" src="https://cloud.githubusercontent.com/assets/381017/22123840/981b37ca-de8d-11e6-8584-ab199752417b.png">

**Comment by EasterPeanut** [comment]
Setting the width to 'auto' for the modx-combo-context won't work for this issue. I've extended the width to 250px.

**Comment by joeke** [comment]
I've tried to fix it with the various options for auto-expanding the list (listWidth, minListWidth, grow, growToLongestValue etc.), but looks like it's not possible.
