### ISSUE TITLE
Duplicate-redirect check is unclear

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#74]
When you try to add an old URL twice, SEO tab notifies you about this and prevents you from adding it twice. The message it uses is unclear though. It currently shows an ID. An ID + Pagetitle would be preferred and it should contain a link to open that resource in an edit-window.

The current text is: http://www.sterc.nl.sytske/nl/oplossingen/ has already been added to resource: (3732)

New one should be something like: http://www.sterc.nl.sytske/nl/oplossingen/ has already been added to resource: [[+pagetitle]](3732) (Edit in new window)

![screen shot 2016-10-25 at 14 58 34](https://cloud.githubusercontent.com/assets/381017/19686937/c2d9dc5e-9ac3-11e6-829f-cba8d37ce5f1.png)

**Comment by gpsietzema** [comment]
This has been changed in 2.0 beta, but it is now completely broken. The link does appear but the placeholder isn't replaced, see screenshot:

<img width="639" alt="screen shot 2017-01-19 at 21 10 08" src="https://cloud.githubusercontent.com/assets/381017/22123401/c02e8f52-de8b-11e6-9399-9aa036a2d49c.png">

**Comment by EasterPeanut** [comment]
Cannot reproduce, the [[+link]] is replaced by '?a=resource/update&id=2'.

**Comment by gpsietzema** [comment]
It is now completely missing:
- From the resource "SEO" tab: Completely missing
- Also missing from the SEO Tab CMP
![screen shot 2017-01-24 at 11 25 20](https://cloud.githubusercontent.com/assets/381017/22243498/d1e3c39e-e227-11e6-85ba-299b28922806.png)
![screen shot 2017-01-24 at 11 24 43](https://cloud.githubusercontent.com/assets/381017/22243499/d2016d04-e227-11e6-8138-da13a2b41bdd.png)

**Comment by Flowan** [comment]
@gpsietzema Fixed
