### ISSUE TITLE
Missing description in the menu

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#78]
Please change the name in the menu to: "SEO Tab" (including space)

Add description to the menu: "Manage all your SEO Tab 301 redirects."

<img width="347" alt="screen shot 2017-01-19 at 15 46 32" src="https://cloud.githubusercontent.com/assets/381017/22111176/adaab6e4-de5e-11e6-80d7-c503ca5874b8.png">

**Comment by joeke** [comment]
@EasterPeanut said this issue was fixed.
