### ISSUE TITLE
SEO Tab CMP improvements

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#79]
Change the introduction from "Here you can view and manage your 301 redirects. Redirects can also be added from the resource create and update pages." to --> "Manage your SEO Tab 301 redirects. Redirects can also be added when editing a resource by click the tab called "SEO"."

Title "SEOTab" --> "SEO Tab"

Button: "Add redirect url" --> "Create 301 redirect"

**Data table**
- Remove ID-column
- "Old url (url to redirect)" --> "Old URL"
- "Target resource / url" --> "New URL / Resource"
- The Context-column shows the contextKey. It would be better to use the context-name

**Add redirect URL dialog window**
- Change title to "Add redirect URL"
- "Old url (url to redirect)" --> "Old URL"
- "Enter the full url (ex. https://www.google.com) you want to redirect" --> "Enter the full URL, including your domain. Example: "https://www.google.com/old-pages/about-us"."
- Is it possible to show context-name instead of context-key?
- Button "Close" --> "Cancel"

<img width="1109" alt="screen shot 2017-01-19 at 15 49 23" src="https://cloud.githubusercontent.com/assets/381017/22111219/de3fe3f6-de5e-11e6-92a6-21582a088dd5.png">

**Comment by joeke** [comment]
@gpsietzema All mentioned changes are done, except for the "Close > Cancel" change, as discussed before. Also fixed a typo ;).
