### ISSUE TITLE
Dialog window height to small when error messages show

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#80]
The dialog window height is to small when the error "This field is required" shows up. Same happens when not selecting a target resource.

Is auto-height possible or something like that?

<img width="659" alt="screen shot 2017-01-19 at 16 08 08" src="https://cloud.githubusercontent.com/assets/381017/22111978/ad47efb6-de61-11e6-8d85-15c41c28a3a3.png">

**Comment by joeke** [comment]
Fixed with https://github.com/Sterc/SEOTab/commit/e624a6a5e2307e30b8973c863f8c42aa52849e1f
