### ISSUE TITLE
301 from Context2 to Context1 results in 404

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#81]
I have 2 contexts:
- web (modx2.gauke)
- other (other.gauke)

301 setup:
Old url: http://other.gauke/test-services
New url: http://modx2.gauke/services

If I go to http://other.gauke/test-services I get the 404-page of the other-context. I'm 100% sure the services-page exists and is published.

<img width="1087" alt="screen shot 2017-01-19 at 16 22 21" src="https://cloud.githubusercontent.com/assets/381017/22112559/af75dc2e-de63-11e6-9e66-ec84c644b60c.png">

**Comment by Flowan** [comment]
@gpsietzema Unable to reproduce. Need more information.

**Comment by gpsietzema** [comment]
Here's more info with audio.

**Comment by Flowan** [comment]
@gpsietzema Fixed
