### ISSUE TITLE
Improvements for the Resource "SEO" tab

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#83]
Button "Add redirect url" --> "Create 301 redirect"
"Below is a list of old URLs for this page" --> "Old URLs redirecting to this page."
"Any change on your page affect search engines. Changing the URL of a page will lead to losing ALL acquired search engine value. With 301 redirects you don’t lose this value. SEOTab automatically adds 301 redirects after changing the URL of a page .." --> "Any change on your page affects search engines, but changing the URL of a page without adding a 301 redirect, will result in losing ALL acquired value. With SEO Tab's 301 redirects your search engine value will be retained! To help prevent this, SEO Tab automatically adds 301 redirects when you change the URL of a page."

Dialog window:
- "Enter the full url (ex. http://www.google.com) you want to redirect" --> "Old URL". Please also add a description below that field in cursive with the text: "Enter the full URL, including your domain. Example: "https://www.google.com/old-pages/about-us"."
- Button "Close" --> "Cancel"

<img width="1113" alt="screen shot 2017-01-19 at 16 33 48 1" src="https://cloud.githubusercontent.com/assets/381017/22112956/1301d990-de65-11e6-801f-cc6eb46fa27a.png">

**Comment by joeke** [comment]
@gpsietzema All the issues are fixed now, except for the 'Close > Cancel', as this is a core lexicon, and would deviate from all other windows in MODX.
