### ISSUE TITLE
Pre-populate target-resource with current domain

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#84]
Is it possible to pre-populate the target-resource field with the current domain and add the cursor behind it when opening the dialog? Like this:

<img width="1043" alt="screen shot 2017-01-19 at 16 40 54" src="https://cloud.githubusercontent.com/assets/381017/22113305/1910ba4e-de66-11e6-9919-06ab17cffe57.png">

Some things to take into consideration:
- In the SEO Tab CMP, you can only pre-populate with the web-context URL (because we don't know what context we're using)
- For the resource-seo-tab we need to pre-populate with the URL of the current context of the resource.

**Comment by Flowan** [comment]
Fixed in https://github.com/Sterc/SEOTab/commit/2ff440be2c5ed78b611ac6c1fff7830bee0e6c3f
