### ISSUE TITLE
301 redirect of the current page URL shouldn't be allowed

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#85]
When I change the URL of a resource, the old URL will be added as a 301. That's expected behaviour. When I do this with the Freeze URI feature, it also works like that, which is also expected behaviour.

In this situation it breaks:
- Freeze URL to some URL
- Save resource (old URL is added as 301 )
- Untick Free URL
- Save resource (old URL is still there)

So in the case of "http://modx2.gauke/services" which I freeze URL to "http://modx2.gauke/serv" and untick to result into ""http://modx2.gauke/services" again, results in a 301 redirect of "http://modx2.gauke/services" + the Resource URL of the current page to be the same. 

There should be a check to see if the current URL is the same as a 301 Redirect to the **same page**. If this is the case for **this page**, it needs to be removed.

**Comment by Flowan** [comment]
@gpsietzema Fixed
