### ISSUE TITLE
noindex should also result into not being included into the sitemap

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#86]
SEO -> Findability -> Include in search engines == "no". This only sets the robots-tag, but should also remove the page from the GoogleSitemap.

**Comment by joeke** [comment]
@gpsietzema Would this mean that the 'Include page in Google Sitemap' option in the 'Google Sitemap' tab would become obsolete?

**Comment by gpsietzema** [comment]
No, that it wont change.

**Comment by joeke** [comment]
@gpsietzema But then you would have 2 options to include/exclude from Google sitemap :S

**Comment by gpsietzema** [comment]
Yes, but think about what happens if you don't do this: If you set
something to not be index and you DO put it in your sitemap, it will be
sent to Google. Google will try to crawl it, but will find out it is
noindex, so it can't crawl it. noindex-pages have nothing to do in a
sitemap.

**Comment by joeke** [comment]
@gpsietzema This should be fixed. Can you confirm this?
