### ISSUE TITLE
Freeze URL text

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#87]
It currently says: "URL after http://modx2.gauke/", where "http://modx2.gauke/" is dynamic.

Please change this to: 
- Bold text: "Freeze URL"
- Description below the bold text in cursive: "Freeze URLs can be used to create short URLs. For example, to set this page URL to http://modx2.gauke/short-url", enter "short-url" in the field below."

**Comment by joeke** [comment]
Fixed with https://github.com/Sterc/SEOTab/commit/4d5c4812b72692fa24ebbfc30d7009b60a01e3e3
