### ISSUE TITLE
Text in SEO -> Findability

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#88]
"Include in search engines" --> "Include in search engines (index/noindex)"
- Option "Yes, this page may be indexed" --> "Yes, include in search engines (index)"
- Option "No, this page should not be indexed (noindex) --> "No, do not include in search engines (noindex)"

"Note: irrelevant pages of your site should be excluded from the search engines and sitemap. Examples of irrelevant pages are: disclaimer, terms and conditions , privacy policy." --> "Irrelevant pages shouldn't be indexed in search engines. Irrelevant page examples: disclaimer, terms and conditions, privacy policy."

"Following links" --> "Follow links (follow/nofollow)"
- Option "Yes, follow links on this page" --> "Yes, follow links on this page (follow)"
- Option "No, don't follow links on this page (nofollow)" --> "Yes, do not follow links on this page (nofollow)"

"Set whether the search engines may or may not follow links on this page" --> "Should search engines follow links on this page."

"Include pages in internal search engine" --> "Include in internal search results"
- Option "Yes, include this page in the internal search engine" --> "Yes, include in internal search results"
- Option "No, hide this page for the internal search engine" --> "No, exclude from internal search results"

"Set whether this page may be included in the internal search results of your website. An example of a page which is redundant in your search results, is the ‘thank you’ page of a contact form." --> "Should this page be included in the internal search results of your website. "Thank you"-pages are good examples of pages which should be excluded."

**Comment by joeke** [comment]
Fixed with https://github.com/Sterc/SEOTab/commit/0fe698ea4d54c71dc13601a4d1f73375024d0d29
