### ISSUE TITLE
Text in SEO -> Google Sitemap

### ISSUE THREAD

**Issue by gpsietzema** [Sterc/SEOTab#89]
Remove this text: "Set whether this page may or may not be included in the sitemap for Google"

"By giving the priority level, you give search engines an indication of the importance of the page. Please note: search engines will not blindly accept your priority level." --> "Set the priority level to indicate to search engines how important a page is. Higher is more important. Please note: search engines will not blindly accept your priority level."

"Specify how often (you expect) the content of this page will be changed." --> "Specify how often you expect the content of this page to change."

**Comment by joeke** [comment]
Fixed
