### ISSUE TITLE
does not work width Tickets in sitemap.xml

### ISSUE THREAD

**Issue by arsentver** [Sterc/SEOTab#90]
StercSeoSiteMap snippet does not display links of resources (Tickets component) in sitemap.xml
Tickets link - https://modx.com/extras/package/tickets

**Comment by gpsietzema** [comment]
Hey @arsentver - Tickets are custom resources which we currently don't support. This might be a nice feature for a 2.1.0 release.

I would suggest we create a system setting with all the classKeys to use (default: modResource), so you can add all the custom resources you want.

**Comment by sdrenth** [comment]
@arsentver @gpsietzema I'm not sure if this is something we can/should fix. Because as long as the custom class extends modResource these resources will be included in the XML sitemap and everything will be just fine. 

Also the tickets extra doesn't seem to exist anymore.
