### ISSUE TITLE
All pages set to noindex,nofollow after installation

### ISSUE THREAD

**Issue by hugopeek** [Sterc/SEOTab#94]
Hi guys,

I just installed StercSEO and added `<meta name="robots" content="[[+seoTab.robotsTag]]">` to the HEAD of each page. But despite the system settings for indexing being set to "yes", they all come out as noindex,nofollow.

Not exactly the desired default behaviour! Am I doing something wrong, or is this a bug?

**Comment by gpsietzema** [comment]
Fixed in release 2.0.0 (to be released).

**Comment by gpsietzema** [comment]
Fixed in 2.0.0.
