### ISSUE TITLE
Possible to add the same URL multiple times in 301 Redirects

### ISSUE THREAD

**Issue by RinzeVanDerBrug** [Sterc/SEOTab#96]
In 301 Redirects, it is possible to add the same URL multiple times. 

When you first add a URL, then save it en then try to add the exact same URL again, you'll receive the error message as you should. 

But when you first add a URL and then add that same URL again and THEN save it, both exact same URLs get added to the oversight.

**Comment by devlanda** [comment]
This issue is fixed with https://github.com/Sterc/SEOTab/pull/170 and will be distributed in the next release of SEOTab.
